export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST';
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS';
export const REMOVE_POST_FAIL = 'REMOVE_POST_FAIL';

export const ADD_POST_TO_ME = 'ADD_POST_TO_ME';
export const REMOVE_POST_OF_ME = 'REMOVE_POST_OF_ME';


export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';


export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const CHANGENICKNAME_REQUEST = 'CHANGENICKNAME_REQUEST'
export const CHANGENICKNAME_SUCCESS = 'CHANGENICKNAME_SUCCESS'
export const CHANGENICKNAME_FAIL = 'CHANGENICKNAME_FAIL'

export const LOAD_POST_REQUEST = 'LOAD_POST_REQUEST'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const LOAD_POST_FAIL = 'LOAD_POST_FAIL'

export const FOLLOW_REQUEST = 'FOLLOW_REQUEST'
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS'
export const FOLLOW_FAIL =    'FOLLOW_FAIL'

export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS'
export const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST'
export const UNFOLLOW_FAIL = 'UNFOLLOW_FAIL'

export const LOAD_MYINFO_SUCCESS = 'LOAD_MYINFO_SUCCESS'
export const LOAD_MYINFO_REQUEST = 'LOAD_MYINFO_REQUEST'
export const LOAD_MYINFO_FAIL = 'LOAD_MYINFO_FAIL'

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'

export const LOAD_USER_POST_SUCCESS = 'LOAD_USER_POST_SUCCESS'
export const LOAD_USER_POST_REQUEST = 'LOAD_USER_POST_REQUEST'
export const LOAD_USER_POST_FAIL = 'LOAD_USER_POST_FAIL'

export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'


export const RETWEET_REQUEST = 'RETWEET_REQUEST'
export const RETWEET_FAIL = 'RETWEET_FAIL'
export const RETWEET_SUCCESS = 'RETWEET_SUCCESS'

export const HASHTAG_POST_REQUEST = 'HASHTAG_POST_REQUEST'
export const HASHTAG_POST_FAIL = 'HASHTAG_POST_FAIL'
export const HASHTAG_POST_SUCCESS = 'HASHTAG_POST_SUCCESS'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'
export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'

export const REPORT_POST_REQUEST = 'REPORT_POST_REQUEST'
export const REPORT_POST_SUCCESS = 'REPORT_POST_SUCCESS'
export const REPORT_POST_FAIL = 'REPORT_POST_FAIL'